l_german:
 SETTING_AUTOSAVE_TO_CLOUD: "In Cloud autospeichern"
 SETTING_SAVE_FILE_FORMAT: "Standard-Speicherformat"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Diese Option wird im Ironman-, Cloud- und Debug-Modus überschrieben"
 OPTION_SAVE_FILE_TEXT: "Text"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Gezippter Text"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Gezipptes Binary"
 SETTING_TOOLTIP_MODE: "Tooltip-Modus"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nLegt fest, wie die Tooltip-Locks aktiviert werden:\n   #b Maustendenz#! – Wird aktiviert, wenn man die Maus auf den Tooltip zubewegt.\n   #b Timer-Lock#! – Wird nach einer bestimmten Frist aktiviert.\n   #b Aktions-Lock#! – Wird mit der mittleren Maustaste aktiviert.\n   #b Timer- oder Aktions-Lock#! – Kann entweder Timer-Lock oder Aktions-Lock verwenden"
 SETTING_TOOLTIP_MODE_NO_LOCK: "Kein Lock"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Maustendenz"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Aktions-Lock (Mausanker)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Timer-Lock (Mausanker)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Aktions-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Timer-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Timer- oder Aktions-Lock"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nLegt die Verzögerung fest, ehe der Tooltip angezeigt wird, wenn der Mauszeiger auf einem Element mit Tooltip ist."
 SETTING_TOOLTIP_DELAY: "Verzögerung anzeigen"
 SETTING_TOOLTIP_UNLOCK_TIME: "Freischaltungsverzögerung"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips freigeschaltet werden."
 SETTING_TOOLTIP_LOCK_TIME: "Lock-Verzögerung"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Lock-Öffnungsverzögerung"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden, während ein anderer Tooltip geöffnet ist."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Fortgeschritten"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Allgemein"
 SETTINGS_CATEGORY_SFX: "Soundeffekte"
 SETTINGS_CATEGORY_MFX: "Musik"
 SETTINGS_CATEGORY_LANGUAGE: "Sprache"
 SETTINGS_CATEGORY_SAVE_GAMES: "Spielstände"
 SETTINGS_CATEGORY_TOOLTIPS: "Tooltip-Einstellungen"
 SETTINGS_CATEGORY_OUTLINER: "Pinnwand"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Kartensteuerung"
 SETTINGS_CATEGORY_MAPMODES: "Kartenmodi"
 SETTING_SHADER_QUALITY: "Shader-Qualität"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Shader-Qualität\n#!Bestimmt die Qualität verschiedener Shader und Effekte.\n\n#T Hoch:#! Verbessert die Qualität einiger Shader-Effekte auf Kosten der Leistung.\n\n#T Mittel:#! Standardeinstellung für die intendierte Grafikerfahrung.\n\n#T Niedrig:#! Diese Einstellung ist für Low-End-Computer gedacht und wird aufgrund des Verlusts an visueller Qualität nicht empfohlen. Eine Reihe von Shadern wird vereinfacht, um die Grafikleistung zu verbessern."
 SETTING_SHOW_NUDITY: "Nacktheit anzeigen"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nLegt fest, ob Charaktere nackt gezeigt werden können."
 SETTING_PAUSE_ON_EVENT: "Pause und Pop-ups bei Ereignissen"
 SETTING_PAUSE_ON_EVENT_TOOLTIP: "#T $SETTING_PAUSE_ON_EVENT$#!\nPausiert das Spiel und zeigt Pop-ups an, wenn Ereignisse ausgelöst werden."
 SETTINGS_CATEGORY_GAME_NOTIFICATIONS: "Benachrichtigungen"
 SETTING_PAUSE_ON_EVENT_MESSAGE_SETTINGS: "$SETTING_PAUSE_ON_EVENT$ (Nur Einzelspieler)"
 SETTING_VALUE_HOURS: "$VALUE|0$ Stunde(n)"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Tagnachtwechsel"
 SETTING_DAYNIGHT_CYCLE: "Tagnachtwechsel aktivieren"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nAktiviert einen Wechsel zwischen Tag und Nacht je nach Sonnenstand."
 SETTING_DAYNIGHT_SYSTEMTIME: "Synchronisierung der Ortszeit aktivieren"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSynchronisiert den Tagnachtwechsel mit der lokalen Uhrzeit des Computers.\n\n#!Überschreibt die Einstellungen des Simulationstempos."
 SETTING_DAYNIGHT_SPEED: "Simulationstempo"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nBestimmt darüber, wie schnell die Zeit zwischen Tag und Nacht wechselt."
 SETTING_SUN_DURATION: "Sonnenstunden"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nBestimmt die Zahl der Sonnenstunden am Tag."
 SETTING_SUNRISE_TIME: "Sonnenaufgangszeit"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nZeitpunkt, an dem die Sonne aufgeht.\n\n#!Wird nur verwendet, wenn die Zeit mit der Ortszeit synchronisiert ist.#!"
 SETTING_DAYNIGHT_SET_TIME: "Manuelle Zeit aktivieren"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nLegt die Tageszeit auf eine bestimmte Stunde fest.\n\n#!Setzt das Simulationstempo außer Kraft und synchronisiert die Ortszeit."
 SETTING_SUNRISE_SET_TIME_HOUR: "Manuelle Stunde"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nLegt die Zeit auf diese Stunde fest.\n\n#!Wird nur verwendet, wenn manuelle Zeit verwendet wird."
 SETTING_BUILDINGS_CUTOFF: "Entfernte Gebäude ausblenden"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\nZeigt immer weniger Gebäude auf der Karte an, je weiter die Kamera entfernt ist.\n\nEs könnte die Leistung verbessern, diese Einstellung zu nutzen."
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "Benachrichtigungen links der Pinnwand"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nDie Benachrichtigungen links der Pinnwand platzieren"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Porträts"
 SETTING_SOUNDTRACK: "Hintergrundmusik"
 SETTING_SOUNDTRACK_TOOLTIP: "Allgemeine Hintergrundmusik"
 SETTING_MUSIC_STINGERS: "Musikanzeiger"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Kurze musikalische Phrasen, die das Gameplay unterstützen."
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Musik"
 SETTING_AMBIENT: "Umgebung"
 SETTING_MUSIC_TOOLTIP: "#T Musiklautstärke\n#!Steuert die Lautstärke der Hintergrundmusik."
 SETTING_AMBIENT_TOOLTIP: "#T Umgebungslautstärke\n#!Steuert die Lautstärke der Umgebungsatmosphäre."
 SETTING_MAP_TOOLTIP_DELAY: "Karten-Tooltip-Verzögerung"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nLegt die Verzögerung fest, bis Karten-Tooltips erscheinen."
 SETTING_MAP_MODE_DELAY: "Kartenmodus-Verzögerung"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Verzögerung vor dem Wechsel in einen neuen Kartenmodus (in Sekunden)"
 SETTING_MAP_MODE_FADE_IN: "Kartenmodus-Einblendung"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Zeit, bis ein neuer Kartenmodus eingeblendet wird, nachdem ein alter ausgeblendet wurde (in Sekunden)"
 SETTING_MAP_MODE_FADE_OUT: "Kartenmodus-Ausblendung"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Zeit, bis ein neuer Kartenmodus ausgeblendet wird, nachdem ein neuer angewendet wurde und die Kartenmodus-Verzögerung verstrichen ist (in Sekunden)"
 SETTING_OCCUPATION_STRIPES: "Schraffierte Besatzungsanzeigen"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nFarbige Streifen als Besatzungsanzeige auf der Karte anstelle von Landesflaggentexturen aktivieren"
 SETTING_PORTRAIT_RENDER_SCALE: "Porträt-Rendering-Skalierung"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nVerbessert den Detailgrad von Charakterporträts durch Hochskalierung der Renderergebnisse auf Kosten einer etwas höheren Renderleistung."
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1,0 – Keine"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1,5 – Mittel"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2,0 – Hoch"
 ui_skin_theme: "Benutzeroberfläche"
 ui_skin_theme_desc: "Die Schaltflächen, Rahmen, Fenster, Kopfzeilen etc. im Spiel."
 papermap_theme: "Papierkarte"
 papermap_theme_desc: "Dies ist die Karte, die Sie sehen, wenn Sie herausgezoomt sind."
 table_top_theme: "Kartentisch"
 table_top_theme_desc: "Wenn Sie auf der Karte so weit wie möglich herauszoomen, können Sie diesen Tisch am oberen und unteren Bildschirmrand sehen."
 table_asset_1_theme: "Tischobjekt (oben links)"
 table_asset_1_theme_desc: "Das oben links neben der Karte auf dem Tisch angezeigte Objekt, wenn man herauszoomt."
 table_asset_2_theme: "Tischobjekt (oben rechts)"
 table_asset_2_theme_desc: "Das oben rechts neben der Karte auf dem Tisch angezeigte Objekt, wenn man herauszoomt."
 table_asset_3_theme: "Tischobjekt (unten links)"
 table_asset_3_theme_desc: "Das unten links neben der Karte auf dem Tisch angezeigte Objekt, wenn man herauszoomt."
 table_asset_4_theme: "Tischobjekt (unten rechts)"
 table_asset_4_theme_desc: "Das unten rechts neben der Karte auf dem Tisch angezeigte Objekt, wenn man herauszoomt."
 table_asset_cloth_theme: "Tischtuch"
 table_asset_cloth_theme_desc: "Das Tuch, auf dem die Münzen ruhen."
 building_sets_themes: "Gebäudesatz"
 color_blind_mode_test: "Test"
