# === [LocEditor:RedundantFile] File contains no active keys, does not exist in English, could be deleted ===

# l_turkish:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
#  Moved key `pm_primary` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_secondary_building_rye_farm` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_secondary_building_wheat_farm` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_secondary_building_rice_farm` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_secondary_building_maize_farm` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_secondary_building_millet_farm` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_no_secondary` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_potatoes` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_vineyards` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_vineyards_building_maize_farm` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_apple_orchards` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_citrus_orchards` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_fig_orchards` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_mulberry_groves` to `game/localization/turkish/production_methods_2_l_turkish.yml`

#  Moved key `pmg_automation` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_automation_building_food_industry` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_automation_building_textile_mills` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_automation_building_furniture_manufacturies` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_automation_building_tooling_workshops` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_automation_building_paper_mills` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_automation_building_steel_mills` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_automation_building_motor_industry` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_civilian_priority` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_military_priority` to `game/localization/turkish/production_methods_2_l_turkish.yml`

  # Textile Mills
#  Moved key `pm_craftsman_sewing` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_sewing_machines` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_electric_sewing_machines` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_traditional_looms` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_mechanized_looms` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_automatic_power_looms` to `game/localization/turkish/production_methods_2_l_turkish.yml`

  # Glassworks
#  Moved key `pm_leaded_glass` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_manual_glassblowing` to `game/localization/turkish/production_methods_2_l_turkish.yml`

  # Chemical Plants
#  Moved key `pm_leblanc_process` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_no_explosives_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_ammonia-soda_process` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_vacuum_evaporation` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_brine_electrolysis` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_fertilizer_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_no_artificial_fertilizers` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_artificial_fertilizers` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_improved_fertilizer` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_nitrogen_fixation` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_dyes_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_no_synthetic_dyes` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pmg_synthetic_dyes` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_silk_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_no_artificial_fibers` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_rayon` to `game/localization/turkish/production_methods_2_l_turkish.yml`

  # Foundries
#  Moved key `pm_steamworks` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_no_artillery_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_artillery_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`

  # Motor Industries
#  Moved key `pmg_automobile_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`
#  Moved key `pm_automobile_production` to `game/localization/turkish/production_methods_2_l_turkish.yml`
