l_simp_chinese:
 SETTING_AUTOSAVE_TO_CLOUD: "自动保存至云端"
 SETTING_SAVE_FILE_FORMAT: "默认存档格式"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "这个选项在铁人、云端和调试模式中不生效"
 OPTION_SAVE_FILE_TEXT: "文本"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "压缩文本"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "压缩二进制"
 SETTING_TOOLTIP_MODE: "弹框提示模式"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\n选择弹框提示如何锁定：\n   #b 鼠标趋向#!——鼠标移动至弹框提示时锁定。\n   #b 时间锁定#!——一定时间后锁定。\n   #b 行动锁定#!——按鼠标中键锁定。\n   #b 时间或行动锁定#!——既可以使用时间锁定也可以使用行动锁定。"
 SETTING_TOOLTIP_MODE_NO_LOCK: "无锁定"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "鼠标趋势"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "动作锁定（鼠标锚点）"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "定时锁定（鼠标锚点）"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "动作锁定"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "定时锁定"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "时间或动作锁定"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\n设置鼠标悬停后显示弹框提示的延时。"
 SETTING_TOOLTIP_DELAY: "显示延迟"
 SETTING_TOOLTIP_UNLOCK_TIME: "解锁的延迟"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n设置弹框提示解锁之前的延时。"
 SETTING_TOOLTIP_LOCK_TIME: "锁定的延迟"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n设置弹框提示锁定之前的延时。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "已开启时的锁定延时"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n设置已打开另一弹框提示时，弹框提示锁定之前的延时。"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "高级"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "通用"
 SETTINGS_CATEGORY_SFX: "音效"
 SETTINGS_CATEGORY_MFX: "音乐"
 SETTINGS_CATEGORY_LANGUAGE: "语言"
 SETTINGS_CATEGORY_SAVE_GAMES: "保存游戏"
 SETTINGS_CATEGORY_TOOLTIPS: "弹框提示设置"
 SETTINGS_CATEGORY_OUTLINER: "概览窗口"
 SETTINGS_CATEGORY_MAP_CONTROLS: "地图控制"
 SETTINGS_CATEGORY_MAPMODES: "地图模式"
 SETTING_SHADER_QUALITY: "着色器质量"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T 着色器质量\n#!决定各种着色器和特效的质量。\n\n#T 高#!以性能为代价提升某些着色器特效的质量。\n\n#T 中#!能获得预期图形体验的默认设置。\n\n#T 低#!这个设置是为低端设备准备的，会造成视觉质量的下降，因此并不推荐。为推动图形性能一些着色器被简化了。"
 SETTING_SHOW_NUDITY: "显示裸体"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\n设定角色是否会显示裸体。"
 SETTING_PAUSE_ON_EVENT: "触发事件时弹出窗口并暂停"
 SETTING_PAUSE_ON_EVENT_TOOLTIP: "#T $SETTING_PAUSE_ON_EVENT$#!\n触发事件时暂停游戏，并显示弹出窗口。"
 SETTINGS_CATEGORY_GAME_NOTIFICATIONS: "通知"
 SETTING_PAUSE_ON_EVENT_MESSAGE_SETTINGS: "$SETTING_PAUSE_ON_EVENT$（仅单人玩家）"
 SETTING_VALUE_HOURS: "$VALUE|0$小时"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "日夜循环"
 SETTING_DAYNIGHT_CYCLE: "启用日夜循环"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\n为太阳运动启用日夜循环。"
 SETTING_DAYNIGHT_SYSTEMTIME: "启用同步本地时间"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\n将日夜循环的速度与时间与电脑本地时间同步。\n\n#!将覆盖模拟速度设置。"
 SETTING_DAYNIGHT_SPEED: "模拟速度"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\n日夜循环的时速。"
 SETTING_SUN_DURATION: "日间小时数"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\n一天中日间的小时数。"
 SETTING_SUNRISE_TIME: "日出时间"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\n太阳升起的时刻。\n\n#!仅在与本地时间同步时生效。#!"
 SETTING_DAYNIGHT_SET_TIME: "启用手动时间"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\n将一天中的时间设置为特定时刻。\n\n#!将覆盖模拟速度和同步本地时间设置。"
 SETTING_SUNRISE_SET_TIME_HOUR: "手动时刻"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\n将时间锁定为这个时刻。\n\n#!仅在手动时间下生效。"
 SETTING_BUILDINGS_CUTOFF: "削减远景建筑物"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\n离镜头的距离越远，地图上显示的建筑物越少。\n\n开启可以提高性能。"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "概览窗口左侧的通知"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\n将消息通知放置在概览窗口左侧"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "肖像"
 SETTING_SOUNDTRACK: "背景音乐"
 SETTING_SOUNDTRACK_TOOLTIP: "总体的背景音乐"
 SETTING_MUSIC_STINGERS: "短乐句"
 SETTING_MUSIC_STINGERS_TOOLTIP: "简短的乐句，强化游玩体验"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "音乐"
 SETTING_AMBIENT: "环境音效"
 SETTING_MUSIC_TOOLTIP: "#T 音乐音量\n#!设置音乐的音量。"
 SETTING_AMBIENT_TOOLTIP: "#T 环境音量\n#!设置环境音效的音量。"
 SETTING_MAP_TOOLTIP_DELAY: "地图弹框提示延迟"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\n设置地图弹框提示出现前的延迟时间。"
 SETTING_MAP_MODE_DELAY: "地图模式延迟"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "切换到新的地图模式的时候会有数秒的延迟"
 SETTING_MAP_MODE_FADE_IN: "地图模式淡入"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "数秒之内，旧的地图模式逐渐淡出，然后新的地图模式逐渐淡入"
 SETTING_MAP_MODE_FADE_OUT: "地图模式淡出"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "当新的地图模式采用之后，当前的地图模式会在地图模式延迟之后的数秒之内逐渐淡出"
 SETTING_OCCUPATION_STRIPES: "条纹占领图像"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\n在地图上使用彩色条纹作为占领区的图像，而不是国家旗帜纹理"
 SETTING_PORTRAIT_RENDER_SCALE: "肖像渲染缩放"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\n通过提高渲染结果缩放来改进角色肖像的细节水平，代价是需要更高的性能用于渲染。"
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1.0 - 无"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1.5 - 中"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2.0 - 高"
 ui_skin_theme: "用户界面"
 ui_skin_theme_desc: "游戏中的按钮、框架、窗口、标题等等。"
 papermap_theme: "纸质地图"
 papermap_theme_desc: "距离拉远时你会看见的地图。"
 table_top_theme: "桌面"
 table_top_theme_desc: "如果你镜头拉至最远，你可以在屏幕上下沿看见桌面。"
 table_asset_1_theme: "桌面物品（左上）"
 table_asset_1_theme_desc: "镜头拉远后，展示于桌面左上、地图旁边的物品。"
 table_asset_2_theme: "桌面物品（右上）"
 table_asset_2_theme_desc: "镜头拉远后，展示于桌面右上、地图旁边的物品。"
 table_asset_3_theme: "桌面物品（左下）"
 table_asset_3_theme_desc: "镜头拉远后，展示于桌面左下、地图旁边的物品。"
 table_asset_4_theme: "桌面物品（右下）"
 table_asset_4_theme_desc: "镜头拉远后，展示于桌面右下、地图旁边的物品。"
 table_asset_cloth_theme: "桌布"
 table_asset_cloth_theme_desc: "放置硬币的桌布。"
 building_sets_themes: "建筑包"
 color_blind_mode_test: "测试"
