#!/usr/bin/env python3
"""Generate the EAFP Japanese culture compatibility patch.

The vanilla culture block owns every non-name field.  EAFP contributes only a
stable union of the four character-name lists.  The current generated file can
be used as the EAFP name source, which makes regeneration idempotent.
"""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


NAME_LISTS = (
    "male_common_first_names",
    "female_common_first_names",
    "noble_last_names",
    "common_last_names",
)


def find_block(text: str, key: str) -> tuple[int, int, str]:
    match = re.search(rf"(?m)^\s*(?:REPLACE:)?{re.escape(key)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"could not find block {key!r}")

    brace = text.index("{", match.start())
    depth = 0
    quoted = False
    escaped = False
    comment = False
    for index in range(brace, len(text)):
        char = text[index]
        if comment:
            if char == "\n":
                comment = False
            continue
        if quoted:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                quoted = False
            continue
        if char == "#":
            comment = True
        elif char == '"':
            quoted = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return match.start(), index + 1, text[match.start() : index + 1]
    raise ValueError(f"unterminated block {key!r}")


def read_names(block: str, key: str) -> list[str]:
    _, _, name_block = find_block(block, key)
    body = name_block[name_block.index("{") + 1 : name_block.rindex("}")]
    names: list[str] = []
    for line in body.splitlines():
        token = line.split("#", 1)[0].strip()
        if not token:
            continue
        if any(character.isspace() for character in token):
            raise ValueError(f"unexpected name token in {key}: {token!r}")
        names.append(token)
    return names


def stable_union(vanilla: list[str], eafp: list[str]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for name in vanilla + eafp:
        normalized = " ".join(name.split()).casefold()
        if normalized not in seen:
            seen.add(normalized)
            result.append(name)
    return result


def replace_name_list(block: str, key: str, names: list[str]) -> str:
    start, end, old = find_block(block, key)
    opening = old[: old.index("{") + 1]
    replacement = opening + "\n" + "\n".join(f"\t\t{name}" for name in names) + "\n\t}"
    return block[:start] + replacement + block[end:]


def build(vanilla_text: str, eafp_text: str, vanilla_hash: str) -> str:
    _, _, vanilla_block = find_block(vanilla_text, "japanese")
    _, _, eafp_block = find_block(eafp_text, "japanese")

    generated = vanilla_block
    counts: list[str] = []
    for key in NAME_LISTS:
        vanilla_names = read_names(vanilla_block, key)
        eafp_names = read_names(eafp_block, key)
        merged = stable_union(vanilla_names, eafp_names)
        generated = replace_name_list(generated, key, merged)
        counts.append(f"{key}={len(merged)}")

    generated = re.sub(
        r"(?m)^\s*japanese\s*=\s*\{",
        "REPLACE:japanese = {",
        generated,
        count=1,
    )
    header = (
        "# Generated by tools/generate_japanese_culture_patch.py\n"
        "# Vanilla baseline: Victoria 3 1.13.11, common/cultures/00_cultures.txt\n"
        f"# Vanilla SHA-256: {vanilla_hash}\n"
        f"# Stable name union: {', '.join(counts)}\n"
        "# Do not hand-edit non-name fields; regenerate after a vanilla update.\n"
    )
    return header + generated.rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("vanilla", type=Path)
    parser.add_argument("target", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    vanilla_bytes = args.vanilla.read_bytes()
    vanilla_text = vanilla_bytes.decode("utf-8-sig")
    eafp_text = args.target.read_text(encoding="utf-8-sig")
    vanilla_hash = hashlib.sha256(vanilla_bytes).hexdigest()
    output = build(vanilla_text, eafp_text, vanilla_hash)

    if args.check:
        if eafp_text.replace("\r\n", "\n") != output:
            raise SystemExit("Japanese culture patch is stale; regenerate it")
        return 0

    # Victoria 3 reports a lexer warning for script files without a UTF-8 BOM.
    args.target.write_text(output, encoding="utf-8-sig", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
