# 이름
name: "Validation"

# 실행 조건
on:
  # 직접 실행
  workflow_dispatch:
  # 풀 리퀘스트
  pull_request:
  # 버전 태그 푸쉬
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[a-z]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+"
  # 모드 출시
  release:
    types:
      - published

# 작업
jobs:
  # 인코딩 확인
  encoding:
    uses: "HaneulCheong/golden-oak-library/.github/workflows/encoding.yml@dev"
